// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3489.Billy.subsystems;

import org.usfirst.frc3489.Billy.RobotMap;
import org.usfirst.frc3489.Billy.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon mShooterL7 = RobotMap.shootermShooterL7;
    private final CANTalon mShooterR8 = RobotMap.shootermShooterR8;
    private final RobotDrive robotDrive21 = RobotMap.shooterRobotDrive21;
    private final CANTalon mIntake6 = RobotMap.armmIntake6;
    private final SpeedController mKicker9 = RobotMap.armmKicker9;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void Spinners() {
    	robotDrive21.tankDrive(-1, -1);
    }
    public void Intaker() {
    	robotDrive21.tankDrive(.5, .5);
    	mIntake6.set(1);
    }
    public void stop() {
    	robotDrive21.drive(0, 0);
    	mIntake6.set(0);
    }
    public void rIntake(){
    	mIntake6.set(-1);
    }
    public void Kicker(){
    	 mKicker9.set(1);
    }
    public void stopKicker() {
    	mKicker9.set(0);
    }

}

